services:
  db:
    image: public.ecr.aws/docker/library/postgres:14
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=DB
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    platform: linux/amd64
    depends_on:
        - db
    build:
      context: ./nutRITion.api/
      dockerfile: ./Dockerfile
  ui:
    platform: linux/amd64
    depends_on:
      - api
    build:
      context: ./nutRITion.ui/nutrition/
      dockerfile: ./Dockerfile
    ports:
    - '69420:3000'


